version: '3.8'
services:
    mongo:
        container_name: mongo
        image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: ''
          MONGO_INITDB_ROOT_PASSWORD: ''
        restart: always
        ports:
          - '27017:27017'
